// panel/site/src/routes/login/+page.svelte
<script lang="ts">
  import { login } from "$lib/api/auth";
  import { goto } from "$app/navigation";
  import { loadUser } from "$lib/stores/auth";

  let username = "";
  let password = "";
  let error = "";
  let loading = false;

  async function handleLogin() {
    if (!username || !password) { error = "Enter username and password"; return; }
    loading = true;
    error = "";
    try {
      await login(username, password);
      await loadUser();
      goto("/");
    } catch (e: unknown) {
      error = e instanceof Error ? e.message : "Login failed";
    } finally {
      loading = false;
    }
  }
</script>

<!-- Background -->
<div class="fixed inset-0 bg-[#0b1326]">
  <div class="absolute inset-0"
    style="background: radial-gradient(ellipse at 20% 80%, rgba(75,226,119,0.05) 0%, transparent 60%), radial-gradient(ellipse at 80% 20%, rgba(13,102,217,0.08) 0%, transparent 60%);">
  </div>
</div>

<div class="relative z-10 flex items-center justify-center h-screen">
  <div class="glass w-full max-w-sm p-8 flex flex-col gap-6">
    <!-- Logo -->
    <div class="flex flex-col items-center gap-2">
      <span class="icon text-primary text-5xl icon-fill">hexagon</span>
      <h1 class="text-on-surface text-xl font-semibold tracking-tight">Hex Panel</h1>
      <p class="text-on-surface-variant text-xs">Sign in to continue</p>
    </div>

    <!-- Form -->
    <form on:submit|preventDefault={handleLogin} class="flex flex-col gap-3">
      <div class="flex flex-col gap-1">
        <label class="text-on-surface-variant text-xs font-medium" for="username">Username</label>
        <input
          id="username"
          type="text"
          bind:value={username}
          autocomplete="username"
          class="bg-surface-container border border-outline-variant rounded-xl px-3 py-2 text-sm text-on-surface outline-none focus:border-primary transition-colors"
          placeholder="admin"
          disabled={loading}
        />
      </div>
      <div class="flex flex-col gap-1">
        <label class="text-on-surface-variant text-xs font-medium" for="password">Password</label>
        <input
          id="password"
          type="password"
          bind:value={password}
          autocomplete="current-password"
          class="bg-surface-container border border-outline-variant rounded-xl px-3 py-2 text-sm text-on-surface outline-none focus:border-primary transition-colors"
          placeholder="••••••••••••"
          disabled={loading}
        />
      </div>

      {#if error}
        <p class="text-error text-xs bg-error-container/20 border border-error/20 rounded-xl px-3 py-2">{error}</p>
      {/if}

      <button
        type="submit"
        disabled={loading}
        class="mt-2 bg-primary text-on-primary rounded-xl py-2.5 text-sm font-semibold transition-opacity disabled:opacity-50 hover:opacity-90"
      >
        {loading ? "Signing in..." : "Sign In"}
      </button>
    </form>
  </div>
</div>

// panel/src/app/auth/login/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';

export default function LoginPage() {
  const [isLogin, setIsLogin] = useState(true);
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    const endpoint = isLogin ? '/api/auth/login' : '/api/auth/register';

    try {
      const res = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, password }),
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || 'Authentication failed');
      }

      router.push('/dashboard');
      router.refresh();
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-950 p-4">
      <div className="w-full max-w-md space-y-8 rounded-xl bg-gray-900 p-8 shadow-2xl border border-gray-800">
        <div className="text-center">
          <h2 className="text-3xl font-bold tracking-tight text-white">
            Hex Panel
          </h2>
          <p className="mt-2 text-sm text-gray-400">
            {isLogin ? 'Sign in to manage your servers' : 'Create an emergency admin account'}
          </p>
        </div>

        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          {error && (
            <div className="rounded-md bg-red-900/50 p-4 border border-red-500/50">
              <div className="text-sm text-red-400">{error}</div>
            </div>
          )}

          <div className="space-y-4 rounded-md shadow-sm">
            <div>
              <label htmlFor="username" className="sr-only">Username</label>
              <input
                id="username"
                name="username"
                type="text"
                required
                className="relative block w-full rounded-md border-0 bg-gray-800 py-2.5 px-3 text-white ring-1 ring-inset ring-gray-700 focus:z-10 focus:ring-2 focus:ring-inset focus:ring-blue-500 sm:text-sm sm:leading-6"
                placeholder="Username"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
              />
            </div>
            <div>
              <label htmlFor="password" className="sr-only">Password</label>
              <input
                id="password"
                name="password"
                type="password"
                required
                className="relative block w-full rounded-md border-0 bg-gray-800 py-2.5 px-3 text-white ring-1 ring-inset ring-gray-700 focus:z-10 focus:ring-2 focus:ring-inset focus:ring-blue-500 sm:text-sm sm:leading-6"
                placeholder="Password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
            </div>
          </div>

          <div>
            <button
              type="submit"
              disabled={loading}
              className="group relative flex w-full justify-center rounded-md bg-blue-600 px-3 py-2.5 text-sm font-semibold text-white hover:bg-blue-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 disabled:opacity-50"
            >
              {loading ? 'Processing...' : (isLogin ? 'Sign in' : 'Create Account')}
            </button>
          </div>
        </form>

        <div className="text-center">
          <button 
            onClick={() => setIsLogin(!isLogin)}
            className="text-sm text-blue-400 hover:text-blue-300"
          >
            {isLogin ? "Need an account? Register" : "Already have an account? Sign in"}
          </button>
        </div>
      </div>
    </div>
  );
}
